export const creatorGuides = new Map([
  [
    "assisted-pushup",
    [
      "https://www.youtube.com/embed/CCZGD55NxGo",
      "https://www.youtube.com/embed/IODxDxX7oi4",
      "https://www.youtube.com/embed/i9sTjhN4Z3M",
    ],
  ],
  [
    "push-up",
    [
      "https://www.youtube.com/embed/IODxDxX7oi4",
      "https://www.youtube.com/embed/i9sTjhN4Z3M",
      "https://www.youtube.com/embed/rruHM_sB2Hc",
    ],
  ],
  [
    "dip",
    [
      "https://www.youtube.com/embed/K5JxupmoLW4",
      "https://www.youtube.com/embed/AGCwEXqW__M",
      "https://www.youtube.com/embed/l41SoWZiowI",
    ],
  ],
  [
    "elbow-lever",
    [
      "https://www.youtube.com/embed/MJrFdfNmIEU",
      "https://www.youtube.com/embed/1Qsh1AChpBg",
    ],
  ],
  [
    "planche-lean",
    [
      "https://www.youtube.com/embed/i33vHrgElkE",
      "https://www.youtube.com/embed/K2CHxTCpWAs",
    ],
  ],
  [
    "pseudo-pu",
    [
      "https://www.youtube.com/embed/C-SML6xnVkI",
      "https://www.youtube.com/embed/odcPqBOlJhI",
    ],
  ],
  [
    "tuck-pl",
    [
      "https://www.youtube.com/embed/M5il8Jpltt8",
      "https://www.youtube.com/embed/3iTGUaMPrHs",
      "https://www.youtube.com/embed/kw6TY9kzZ0I",
    ],
  ],
  [
    "tuck-pl-pu",
    [
      "https://www.youtube.com/embed/N2sLMih8fP4",
      "https://www.youtube.com/embed/4IISjdSCw5k",
    ],
  ],
  [
    "adv-tuck-pl",
    [
      "https://www.youtube.com/embed/0YS3NkbLOgk",
      "https://www.youtube.com/embed/52kD1wrjYy8",
      "https://www.youtube.com/embed/ZayL0dse094",
    ],
  ],
  ["adv-tuck-pl-pu", ["https://www.youtube.com/embed/6dEBUv-OJIg"]],

  [
    "pike-pu",
    [
      "https://www.youtube.com/embed/fXgou2W10ok",
      "https://www.youtube.com/embed/0cT6ug3WVn4",
      "https://www.youtube.com/embed/RuGjXUHRYSI",
    ],
  ],
  [
    "crow-pose",
    [
      "https://www.youtube.com/embed/kdB-UJg3s-Q",
      "https://www.youtube.com/embed/ysTXf7DVOf0",
    ],
  ],
  ["assisted-hs", ["https://www.youtube.com/embed/xMFRkQpXVoI"]],
  [
    "handstand",
    [
      "https://www.youtube.com/embed/_gntsmIZvbI",
      "https://www.youtube.com/embed/aXDxa79u0xQ",
      "https://www.youtube.com/embed/2H2yLngOZdg",
    ],
  ],
  [
    "elevated-pike-pu",
    [
      "https://www.youtube.com/embed/5IcgscNCId8",
      "https://www.youtube.com/embed/8URA3YSur2M",
    ],
  ],
  [
    "bas",
    [
      "https://www.youtube.com/embed/y67yQ6qa0qQ",
      "https://www.youtube.com/embed/D3ZWTQww7Yk",
    ],
  ],
  ["assisted-hspu", ["https://www.youtube.com/embed/6MdyYIRS7FY"]],
  [
    "hspu",
    [
      "https://www.youtube.com/embed/RcrIYne-Yrg",
      "https://www.youtube.com/embed/H65sLbCNCTY",
      "https://www.youtube.com/embed/7wSZnHQZChI",
    ],
  ],

  ["assisted-inv-row", ["https://www.youtube.com/embed/1F0yf-v_Qng"]],
  [
    "inverted-row",
    [
      "https://www.youtube.com/embed/5W8F6MzZ8Rk",
      "https://www.youtube.com/embed/2Synad5Yo-g",
    ],
  ],
  [
    "tuck-fl",
    [
      "https://www.youtube.com/embed/lkGhntOoLNk",
      "https://www.youtube.com/embed/BwhZYpIdhro",
    ],
  ],
  ["tuck-fl-row", ["https://www.youtube.com/embed/o1hChkroodA"]],
  ["pike-fl", ["https://www.youtube.com/embed/YVKsrcjyuYY"]],
  [
    "pike-fl-row",
    [
      "https://www.youtube.com/embed/5OYql7-JNwk",
      "https://www.youtube.com/embed/jWm9I0M-3f0",
    ],
  ],
  ["adv-tuck-fl", ["https://www.youtube.com/embed/D-dOt8Ey5Ig"]],
  ["super-adv-tuck-fl", ["URL", "URL", "URL"]],
  [
    "adv-tuck-fl-row",
    [
      "https://www.youtube.com/embed/4DZPaCOfJOI",
      "https://www.youtube.com/embed/9wd-EzPkwPY",
    ],
  ],
  [
    "straddle-fl",
    [
      "https://www.youtube.com/embed/yUc5Lxe80c8",
      "https://www.youtube.com/embed/1I5K5wnuIaM",
      "https://www.youtube.com/embed/FHdu3mTP0Vs",
    ],
  ],
  ["straddle-fl-row", ["URL", "URL", "URL"]],
  ["half-lay-fl", ["https://www.youtube.com/embed/JdWhaZlb2rw"]],
  [
    "full-fl",
    [
      "https://www.youtube.com/embed/AGhb8V8M758",
      "https://www.youtube.com/embed/sDz16P6gdkk",
      "https://www.youtube.com/embed/HEpf42Z_Dck",
      "https://www.youtube.com/embed/dsIkuWgzoBs",
      "https://www.youtube.com/embed/abT3pEtoBh4",
      "https://www.youtube.com/embed/eC5JKwac4jc",
    ],
  ],

  [
    "deadhang",
    [
      "https://www.youtube.com/embed/3i2kPN5w3Eg",
      "https://www.youtube.com/embed/PlAE67ovNEo",
    ],
  ],
  [
    "activehang",
    [
      "https://www.youtube.com/embed/rwCW8Q-odQY",
      "https://www.youtube.com/embed/GwMTIwfOPQE",
    ],
  ],
  ["assist-pullup", ["https://www.youtube.com/embed/ZHllQTJf7eA"]],
  [
    "pull-up",
    [
      "https://www.youtube.com/embed/aNUSgyWRJYA",
      "https://www.youtube.com/embed/tB3X4TjTIes",
      "https://www.youtube.com/embed/MA2yaxzOgyg",
    ],
  ],
  [
    "chest-pull-up",
    [
      "https://www.youtube.com/embed/SmduaQzt8Jk",
      "https://www.youtube.com/embed/zLDKemkGuzg",
    ],
  ],
  [
    "waist-pull-up",
    [
      "https://www.youtube.com/embed/s85LNjqQknM",
      "https://www.youtube.com/embed/WDs7DUwMk7g",
    ],
  ],
  [
    "muscle-up",
    [
      "https://www.youtube.com/embed/w016kSjobr8",
      "https://www.youtube.com/embed/KGGWP695Zx4",
    ],
  ],
  [
    "situp",
    [
      "https://www.youtube.com/embed/UMaZGY6CbC4",
    ],
  ],
  [
    "hollowbody",
    [
      "https://www.youtube.com/embed/uZqTUwq96iU",
    ]
  ],
  [
    "l-sit-comp",
    [
      "https://www.youtube.com/embed/G1_EoDs-G7E",
    ]
  ],
  [
    "l-sit",
    [
      "https://www.youtube.com/embed/H_iZG5-L_KI",
      "https://www.youtube.com/embed/WS4p5SMkpFA",
      "https://www.youtube.com/embed/RkLUSpe1Ilk",
    ]
  ],
  [
    "dragon-flag",
    [
      "https://www.youtube.com/embed/pvz7k5gO-DE",
      "https://www.youtube.com/embed/dSrAKXMmB7Y",
      "https://www.youtube.com/embed/7fRemwjcXOQ&pp=ygUKI2RyYWdvbmxlZ9IHCQn3AIUdvf8Vzg%3D%3D",
    ]
  ],
  [
    "scapula-pull-up",
    [
      "https://www.youtube.com/embed/1yxFXaH3rtE",
      "https://www.youtube.com/embed/-ZIpSoTRsuE",
    ]
  ],
  [
    "ninety-deg-hold",
    [
      "https://www.youtube.com/embed/RtCGENqaH9U",
      "https://www.youtube.com/embed/zJdq44mdZrE",
      "https://www.youtube.com/embed/Jeew_oxr5ZA"
    ]
  ]
]);
