export const skillDiff = new Map([
  ["Assisted Push-up", "F"],
  ["Push-up", "F"],
  ["Dip", "D"],
  ["Elbow Lever", "D"],
  ["Planche Lean", "C"],
  ["Pseudo Push-up", "C"],
  ["Tuck Planche", "B"],
  ["Tuck Planche PU", "B"],
  ["Adv. Tuck Planche", "B"],
  ["Adv. Tuck Planche PU", "B"],
  ["90 Degree Hold", "B"],
  ["Back Lever", "A"],
  ["Super Adv. Tuck PL", "A"],
  ["Straddle Planche", "A"],
  ["Straddle Planche PU", "A"],
  ["Half Lay Planche", "A"],
  ["Full Planche", "S"],
  ["Full Planche PU", "SS"],
  ["One Arm Planche", "SS"],
  ["Maltese", "SS"],

  //HORIZONTAL PUSH SKILLS ^^^

  ["Pike Push-up", "C"],
  ["Crow Pose", "C"],
  ["Assisted Handstand", "C"],
  ["Handstand", "C"],
  ["Elevated Pike PU", "B"],
  ["Bent Arm Press to HS", "B"],
  ["Straight Arm Press to HS", "B"],
  ["Bent Arm Stand", "B"],
  ["Assisted HSPU", "B"],
  ["HSPU", "B"],
  ["Deep HSPU", "A"],
  ["90 Degree PU", "A"],
  ["Assisted OAHS", "A"],
  ["OAHS", "A"],
  ["OA Flag", "A"],

  // VERTICAL PUSH SKILLS ^^^

  ["Assisted Inverted Row", "F"],
  ["Inverted Row", "F"],
  ["Tuck FL", "C"],
  ["Tuck FL Row", "C"],
  ["Pike FL", "C"],
  ["Pike FL Row", "C"],
  ["Adv. Tuck FL", "B"],
  ["Super Adv. Tuck FL", "A"],
  ["Adv. Tuck FL Row", "A"],
  ["Straddle FL", "A"],
  ["Straddle FL Row", "A"],
  ["Half Lay FL", "A"],
  ["Full Front Lever", "A"],
  ["Full FL Row", "A"],
  ["Front Lever Touch", "S"],

  // HORIZONTAL PULL SKILLS^^^

  ["Deadhang", "F"],
  ["Active Hang", "F"],
  ["Assisted Pull-up", "D"],
  ["Pull-up", "D"],
  ["Scapula Pull-up", "D"],
  ["Chest Pull-up", "C"],
  ["Waist Pull-up", "B"],
  ["Muscle-Up", "B"],
  ["Archer Pull-up", "B"],
  ["Clean Muscle-Up", "A"],
  ["Assisted OAC", "A"],
  ["Assisted OAP", "A"],
  ["OAC/OAP", "A"],
  ["Weighted Pull-ups", "Scalable"],
  ["Butterfly", "SS"],


  //VERTICAL PULL SKILLS ^^

  ["Bodyweight Squat", "F"],
  ["Split Squat", "F"],
  ["Assisted Pistol Squat", "D"],
  ["Bulgarian Split Squat", "D"],
  ["Reverse Nordic Curl", "C"],
  ["Nordic Curl", "C"],
  ["Sissy Squat", "C"],
  ["Pistol Squat", "C"],
  ["Shrimp Squat", "B"],
  ["Dragon Pistol Squat", "B"],

  //LEG SKILLS ^^^

  ["Sit-up", "F"],
  ["Hollow Body Hold", "F"],
  ["L-sit Compression", "D"],
  ["L-sit", "D"],
  ["Dragon Flag", "C"],
  ["V-sit", "B"],
  ["I-sit", "B"],
  ["Manna", "A"],
  ["Human Flag", "B"],
  ["Victorian", "S"],
]);
