export const skillLinks = new Map([
    ["Assisted Push-up", "/tutorials/assistedpu"],
    ["Push-up", "/tutorials/pushup"],
    ["Dip", "/tutorials/dip"],
    ["Elbow Lever", "/tutorials/elbowlever"],
    ["Planche Lean", "/tutorials/planchelean"],
    ["Psuedo Push-up", "/tutorials/psuedopu"],
    ["Tuck Planche", "/tutorials/tuckpl"],
    ["Tuck Planche PU", "/tutorials/tuckplpu"],
    ["Adv. Tuck Planche", "/tutorials/advtuckpl"],
    ["Adv. Tuck Planche PU", "adv. tuck planche pu"],
    ["90 Degree Hold", "90 degree hold"],
    ["Back Lever", "back lever"],
    ["Super Adv. Tuck Planche", "super adv. tuck planche"],
    ["Straddle Planche", "straddle planche"],
    ["Straddle Planche PU", "straddle planche pu"],
    ["Half Lay Planche", "half lay planche"],
    ["Full Planche", "full planche"],
    ["Full Planche PU", "full planche pu"],
    ["One Arm Planche", "one arm planche"],
    ["Maltese", "maltese"],
  
    //HORIZONTAL PUSH SKILLS ^^^
  
    ["Pike Push-up", "/tutorials/pikepu"],
    ["Crow Pose", "/tutorials/crowpose"],
    ["Assisted Handstand", "/tutorials/assistedhs"],
    ["Handstand", "/tutorials/handstand"],
    ["Elevated Pike PU", "/tutorials/elevatedpikepu"],
    ["Bent Arm Press to HS", "bent arm press to hs"],
    ["Straight Arm Press to HS", "straight arm press to hs"],
    ["Bent Arm Stand", "/tutorials/bas"],
    ["Assisted HSPU", "/tutorials/assistedhspu"],
    ["HSPU", "hspu"],
    ["Deep HSPU", "deep hspu"],
    ["90 Degree PU", "90 degree pu"],
    ["Assisted OAHS", "assisted oahs"],
    ["OAHS", "oahs"],
    ["OA Flag", "oa flag"],
  
    // VERTICAL PUSH SKILLS ^^^
  
    ["Assisted Inverted Row", "/tutorials/assistedinvrow"],
    ["Inverted Row", "/tutorials/invertedrow"],
    ["Tuck FL", "/tutorials/tuckfl"],
    ["Tuck FL Row", "/tutorials/tuckflrow"],
    ["Pike FL", "/tutorials/pikefl"],
    ["Pike FL Row", "/tutorials/pikeflrow"],
    ["Adv. Tuck FL", "/tutorials/advtuckfl"],
    ["Super Adv. Tuck FL", "/tutorials/superadvtuckfl"],
    ["Adv. Tuck FL Row", "/tutorials/advtuckflrow"],
    ["Straddle FL", "/tutorials/straddlefl"],
    ["Straddle FL Row", "/tutorials/straddleflrow"],
    ["Half Lay FL", "/tutorials/halflayfl"],
    ["Full Front Lever", "/tutorials/fullfl"],
    ["Full FL Row", "full fl row"],
    ["Front Lever Touch", "front lever touch"],
  
    // HORIZONTAL PULL SKILLS^^^
  
    ["Deadhang", "/tutorials/deadhang"],
    ["Active Hang", "/tutorials/activehang"],
    ["Assisted Pull-up", "/tutorials/assistpullup"],
    ["Pull-up", "/tutorials/pullup"],
    ["Scapula Pull-up", "scapula pull-up"],
    ["Chest Pull-up", "/tutorials/chestpullup"],
    ["Waist Pull-up", "/tutorials/waistpullup"],
    ["Muscle-Up", "/tutorials/muscleup"],
    ["Archer Pull-up", "archer pull-up"],
    ["Clean Muscle-Up", "clean muscle-up"],
    ["Assisted OAC", "assisted oac"],
    ["Assisted OAP", "assisted oap"],
    ["OAC/OAP", "oac/oap"],
    ["Weighted Pull-ups", "weighted pull-ups"],
    ["Butterfly", "butterfly"],
  
    //VERTICAL PULL SKILLS ^^
  
    ["Bodyweight Squat", "bodyweight squat"],
    ["Split Squat", "split squat"],
    ["Assisted Pistol Squat", "assisted pistol squat"],
    ["Bulgarian Split Squat", "bulgarian split squat"],
    ["Assisted Shrimp Squat", "assisted shrimp squat"],
    ["Sissy Squat", "sissy squat"],
    ["Pistol Squat", "pistol squat"],
    ["Shrimp Squat", "shrimp squat"],
    ["Dragon Squat", "dragon squat"],
    ["Dragon Pistol Squat", "dragon pistol squat"],
  
    //LEG SKILLS ^^^
  ]);
  