export const skillTime = new Map([
  ["Assisted Push-up", "~1 week"],
  ["Push-up", "1-2 weeks"],
  ["Dip", "2-4 weeks"],
  ["Elbow Lever", "2-4 weeks"],
  ["Planche Lean", "3-5 weeks"],
  ["Psuedo Push-up", "1-2 months"],
  ["Tuck Planche", "3-6 months"],
  ["Tuck Planche PU", "4-7 months"],
  ["Adv. Tuck Planche", "6-12 months"],
  ["Adv. Tuck Planche PU", "9-15 months"],
  ["90 Degree Hold", "12-15 months"],
  ["Back Lever", "15-18 months"],
  ["Super Adv. Tuck Planche", "1-2 years"],
  ["Straddle Planche", "1-3 years"],
  ["Straddle Planche PU", "2-3 years"],
  ["Half Lay Planche", "2-4 years"],
  ["Full Planche", "3-5 years"],
  ["Full Planche PU", "3-5 years"],
  ["One Arm Planche", "4-6 years"],
  ["??????", "??????"],

  //HORIZONTAL PUSH SKILLS ^^^

  ["Pike Push-up", "2-3 months"],
  ["Crow Pose", "1-2 months"],
  ["Assisted Handstand", "1-2 months"],
  ["Handstand", "2-3 months"],
  ["Elevated Pike PU", "3-9 months"],
  ["Bent Arm Stand", "6-12 months"],
  ["Assisted HSPU", "9-12 months"],
  ["HSPU", "1-2 years"],
  ["Deep HSPU", "2-3 years"],
  ["90 Degree PU", "2-3 years"],
  ["Assisted OAHS", "1-3 years"],
  ["OAHS", "2-3 years"],

  // VERTICAL PUSH SKILLS ^^^

  ["Assisted Inverted Row", "1-2 weeks"],
  ["Inverted Row", "1-2 weeks"],
  ["Tuck FL", "2-4 months"],
  ["Tuck FL Row", "2-4 months"],
  ["Pike FL", "4-6 months"],
  ["Pike FL Row", "4-6 months"],
  ["Adv. Tuck FL", "5-8 months"],
  ["Super Adv. Tuck FL", "6-12 months"],
  ["Adv. Tuck FL Row", "6-12 months"],
  ["Straddle FL", "9-18 months"],
  ["Straddle FL Row", "12-18 months"],
  ["Half Lay FL", "12-18 months"],
  ["Full Front Lever", "1-2 years"],
  ["Full FL Row", "1-2 years"],
  ["Front Lever Touch", "1-2 years"],

  //HORIZONTAL PULL SKILLS ^^
]);
